"""empty message

Revision ID: 49e24c8aa77d
Revises: 83e71d861575
Create Date: 2023-03-14 14:54:01.748468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e24c8aa77d'
down_revision = '83e71d861575'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
